import type { AppBootstrap } from './types'

export const mockBootstrap: AppBootstrap = {
  connectionProfiles: [
    { name: 'prod-edge', target: 'deploy@edge-01.example.com:22', auth: 'ed25519' },
    { name: 'media-origin', target: 'ops@origin.internal:22', auth: 'password' },
  ],
  session: {
    connectionState: 'Connected',
    protocolMode: 'SFTP primary',
    host: 'deploy@edge-01.example.com',
    authMethod: 'SSH key',
    trustState: 'Known host verified',
  },
  panes: {
    local: {
      id: 'local',
      title: 'Local',
      location: '/home/cyberdyne/projects/warp',
      filter: '',
      itemCount: 8,
      selectedCount: 2,
      entries: [
        { name: 'src', kind: 'dir', size: '', modified: 'Today 17:34', permissions: 'drwxr-xr-x' },
        { name: 'src-tauri', kind: 'dir', size: '', modified: 'Today 18:19', permissions: 'drwxr-xr-x' },
        { name: 'package.json', kind: 'file', size: '841 B', modified: 'Today 18:18', permissions: '-rw-r--r--' },
        { name: 'package-lock.json', kind: 'file', size: '42 KB', modified: 'Today 18:18', permissions: '-rw-r--r--' },
        { name: 'vite.config.ts', kind: 'file', size: '196 B', modified: 'Today 18:18', permissions: '-rw-r--r--' },
        { name: 'tsconfig.app.json', kind: 'file', size: '689 B', modified: 'Today 18:17', permissions: '-rw-r--r--' },
        { name: '.github', kind: 'dir', size: '', modified: 'Today 18:26', permissions: 'drwxr-xr-x' },
        { name: 'README.md', kind: 'file', size: '3.1 KB', modified: 'Today 18:26', permissions: '-rw-r--r--' },
      ],
    },
    remote: {
      id: 'remote',
      title: 'Remote',
      location: '/srv/www/releases/current',
      filter: '',
      itemCount: 9,
      selectedCount: 1,
      entries: [
        { name: 'assets', kind: 'dir', size: '', modified: 'Today 17:12', permissions: 'drwxr-xr-x' },
        { name: 'config', kind: 'dir', size: '', modified: 'Today 17:15', permissions: 'drwxr-x---' },
        { name: 'public', kind: 'dir', size: '', modified: 'Today 17:09', permissions: 'drwxr-xr-x' },
        { name: 'storage', kind: 'dir', size: '', modified: 'Today 16:58', permissions: 'drwxrwx---' },
        { name: '.env.production', kind: 'file', size: '1.4 KB', modified: 'Today 16:40', permissions: '-rw-------' },
        { name: 'index.php', kind: 'file', size: '1.8 KB', modified: 'Today 17:20', permissions: '-rw-r--r--' },
        { name: 'release.json', kind: 'file', size: '732 B', modified: 'Today 16:55', permissions: '-rw-r--r--' },
        { name: 'var', kind: 'symlink', size: '', modified: 'Today 16:58', permissions: 'lrwxrwxrwx' },
        { name: 'vendor', kind: 'dir', size: '', modified: 'Today 16:49', permissions: 'drwxr-xr-x' },
      ],
    },
  },
  transfers: [
    {
      id: '1',
      protocol: 'SFTP',
      direction: 'Upload',
      name: 'release.json',
      path: '/home/cyberdyne/projects/warp/release.json -> /srv/www/releases/current/release.json',
      rate: '19.4 MB/s',
      progress: '81%',
      state: 'Running',
    },
    {
      id: '2',
      protocol: 'SFTP',
      direction: 'Download',
      name: 'logs-2026-03-13.tar.gz',
      path: '/srv/backups/logs-2026-03-13.tar.gz -> /home/cyberdyne/Downloads',
      rate: 'Completed',
      progress: '100%',
      state: 'Complete',
    },
    {
      id: '3',
      protocol: 'SCP compatibility',
      direction: 'Upload',
      name: 'hotfix.patch',
      path: '/home/cyberdyne/projects/warp/hotfix.patch -> /tmp/hotfix.patch',
      rate: 'Queued',
      progress: '0%',
      state: 'Queued',
    },
  ],
  shortcuts: ['Tab pane', 'Ctrl+L path', 'Ctrl+F filter', 'F2 rename', 'Delete remove'],
}
